package org.polarmeet.api.entities;

import jakarta.persistence.*;

@Entity
@Table(name = "users")
public class User {

    @Id // marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // configures the ID to be auto-generated by the DB
    private Long id;

    private String name;
    private String email;

    // --- New field ---
    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public User() {} // required by JPA

    public User(String name, String email) {
       this.name = name;
       this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
